### ISSUE TITLE
Update the one-paragraph introduction on our official page according to the approved charter

### ISSUE THREAD

**Issue by lianghai** [w3c/font-text-cg#21]
The text on our [CG official page](https://www.w3.org/community/font-text/)—

> The Font and Text community group gathers individuals and organisations to discuss and develop specifications and implementations for technologies such as shaping and layout which operate on and at the interface between text encoding and font formats.

—should now be updated to match the now approved charter’s [section of Goals](https://github.com/w3c/font-text-cg/blob/main/charter/index.md#goals).

**Comment by xfq** [comment]
I couldn't find the interface to modify the CG introduction. Maybe @koalie or @ianbjacobs knows more?

**Comment by ianbjacobs** [comment]
@xfq and @lianghai, I've made the change; let me know if further action is needed. All the best!
