### ISSUE TITLE
[Meeting 4 action] Zoom account

### ISSUE THREAD

**Issue by lianghai** [w3c/font-text-cg#30]
Per [Meeting 4 action](https://github.com/w3c/font-text-cg/blob/main/minutes/meeting-20201019-4.md#actions):

> - Ask W3C for a dedicated video meeting space.

I’ve found this page: https://w3c.github.io/Guide/meetings/zoom.html —However the page doesn’t seem to explain how to apply for the linked MIT service as a W3C participant.

@svgeesus, @xfq, @fantasai, and @frivoal:

Is it possible for a CG to benefit from that Zoom arrangement?

**Comment by xfq** [comment]
I am happy to help create Zoom rooms if needed.

**Comment by lianghai** [comment]
@xfq, yes please! We’ve just decided to schedule this meeting for [20:30–22:00 UTC on Tue 17 Nov](https://everytimezone.com/s/8537c56f) (see #28).

**Comment by lianghai** [comment]
Done. Fuqiao has set up a Zoom meeting room for us! Gonna share it in the internal mailing list.
