### ISSUE TITLE
Next meeting, when and where

### ISSUE THREAD

**Issue by lianghai** [w3c/font-text-cg#6]
Meeting 4 is has been scheduled:

- **When:** Mon 19 Oct, 16:00–17:30 UTC
  - Confirmed by the [Doodle poll](https://doodle.com/poll/pbr542e5uafawbpa) on 8 October.
- **Where:** https://meet.google.com/ayg-mnmp-fit

We’ll also start using IRC (#7) for meeting management.

**Comment by lianghai** [comment]
@davelab6: Can we modify the https://meet.google.com/ayg-mnmp-fit meeting room’s title to something like “W3C Font and Text Community Group”, in order to reflect this group’s identity and avoid confusion? Last time it still showed something starting with “MPEG Open Font Format”.

**Comment by xfq** [comment]
Although it has little effect on the participant of this group, just FYI - October is W3C's TPAC month and the meeting time may conflict with some group meetings for W3C people.

See the schedule here: https://www.w3.org/2020/10/TPAC/group-schedule.html

**Comment by lianghai** [comment]
The schedule has been confirmed as “Mon 19 Oct, 16:00–17:30 UTC” by the [Doodle poll](https://doodle.com/poll/pbr542e5uafawbpa) on 8 October. An issue has been created for the agenda: #17 

This timing doesn’t seem to overlap with significantly relevant TPAC meetings, although I don’t expect many W3C experts to have enough energy to also attend this FTCG meeting on that day.
